### ISSUE TITLE
Remember last shape on page reload

### ISSUE THREAD

**Issue by pavel-voronin** [tobspr/shapez.io-viewer#18]
We have no shape history so let's protect the last one

**Comment by 1000i100** [comment]
an other way could be to use pushstate to update url with the last successful shape -> browser history is usable to go back and the shape code is sharable even whout using the share button

**Comment by mekb-turtle** [comment]
i've read the code, and you can use the query as such `/?RuCw--Cw.----Ru--` would be `RuCw--Cw:----Ru--`

**Comment by sophuric** [comment]
1 year later....
